- name: Build EXE
  run: |
    pyinstaller --onefile --noconsole --name contact_extractor dragdrop_contacts.py
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile dragdrop_contacts.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-contact-extractor-exe
          path: dist/dragdrop_contacts.exe
